- src/components/Main/Scenario/ScenarioCardPopulation.tsx
> added simple disclaimer distinguishing total from available healthcare capacity

- README.md
Readme file is the face of any repository. This adds some usual grooming to the top part. More work is necessary on the text of the body of the document.
https://github.com/neherlab/covid19_scenarios/issues/16
Community and reach
None necessary
None
> docs(readme): add header and badges to readme

- README.md
- src/components/Main/Scenario/ScenarioCardEpidemiological.tsx
- src/components/Main/Scenario/SeverityCard.tsx
Add an overview of the project to the readme and adjust labels for parameters 
None, only added explanation
> add overview paragraph to readme and update descriptions 

- README.md
This adds "Discover" section to the readme, including the chat button
> doc(readme): add "Discover" section

- src/components/Main/Results/ResultsCard.tsx
- src/index.ejs
- src/styles/global.scss
1) Adds smooth scroll functionality once the Result button is clicked. 
2) Add disabled cursor for all disabled buttons (Disabled buttons had cursor:pointer before)
https://github.com/neherlab/covid19_scenarios/issues/71 - Point number 4
1) Result button click.
> Auto Scroll To View Results on Mobile

- config/jest/jest.tests.config.js
- config/jest/mockPopperJS.js
- src/components/Form/FormHelpButton.test.tsx
- src/components/Form/FormHelpButton.tsx
Tests the FormHelpLabel component.
- Contributes to https://github.com/neherlab/covid19_scenarios/issues/19
Unit tests.
`yarn test`
None.
> Form help popover unit test

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
This adds/updates issue templates for bug reports, feature requests, and documentation.
- Contributes to https://github.com/neherlab/covid19_scenarios/issues/16
> Update issue templates

- cypress/integration/results.spec.ts
- src/components/Main/Results/AgeBarChart.tsx
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/OutcomeRatesTable.tsx
- src/components/Main/Results/ResultsCard.tsx
#119 
Added few data-testid's for results charts
run `yarn e2e:dev`
I hope this is helpful
> test: add e2e tests for results charts

- src/components/Form/FormLabel.test.tsx
- src/components/Form/HelpLabel.test.tsx
a few more tests for the form label components
Contributes to https://github.com/neherlab/covid19_scenarios/issues/19
React component unit tests
`yarn test`
None.
> issue #19: a few more tests for the form label components

- README.md
-Added user guide. Still needs editing but once is up to standard would likely be helpful to add to the tool's website itself. 
-Added Code Stack and Code Examples section under development, these still need to be done but figured it would be good to add in case anybody wanted to add their own
Let me know thoughts, thx!
Updated README to include a user guide and additional development resources (code stack and code examples sections). 
N/A
README.md
> Update README.md with user guide

- src/components/Main/Scenario/ScenarioCard.tsx
- src/components/Main/Scenario/ScenarioCardContainment.tsx
- src/components/Main/Scenario/ScenarioCardPopulation.tsx
- src/components/Main/Scenario/SeverityCard.tsx
- src/components/Main/Scenario/SeverityTable.tsx
- src/components/Main/Scenario/severityTableUpdate.ts
Addressing the easiest linting wins in `src/components/Scenario`.
None.
> Easiest linting wins for #101 in Scenario components

- src/components/Form/FormHelpButton.tsx
- src/components/LanguageSwitcher/index.tsx
- src/pages/ErrorPage.tsx
- src/pages/NotFound.tsx
Addressing some more of the easiest linting wins in `src/components/` and `src/pages/`.
None.
> Easiest linting wins for #101 in components & pages

- src/helpers/hooks.ts
- src/index.polyfilled.ts
- src/server/server.ts
- src/state/util/fsaImmerReducer.ts
Addressing some of the easiest linting wins in `src/`.
None.
> Easiest linting wins for #101

- src/algorithms/test/model.test.ts
Fixes all remaining linter warnings in `src/algorithms/test/model.test.ts`.
#101 
Unit tests.
`yarn test:lint model`
> #101/Final linter fixes for model tests.

- src/assets/text/faq.md
- src/components/Layout/Layout.scss
- src/components/Layout/Layout.tsx
- src/pages/ErrorPage.tsx
- src/pages/Loading.tsx
- src/pages/NotFound.tsx
- src/pages/Team.tsx
Uses container/row/col on all pages to make them a little bit saner. Except the landing page i.e. scenario which has its own full width thing going on.
Someone else might tackle the h1-* CSS 😱 
Contributes to https://github.com/neherlab/covid19_scenarios/issues/148
Pages.
`yarn prod && yarn prod:serve`
> Page prettification

- src/algorithms/utils/TimeSeries.ts
- src/algorithms/utils/exportResult.ts
- src/components/Form/CardWithDropdown.tsx
- src/components/Main/Disclaimer.tsx
- src/components/Main/Main.tsx
- src/components/Main/Results/OutcomeRatesTable.tsx
- src/components/Main/Scenario/ScenarioCardPopulation.tsx
Addressing some more linting easy wins in `components` and `algorithms`.
None.
> More linting easy wins for #101 in components and algorithms

- cypress/integration/language.spec.ts
- cypress/integration/navigation.spec.ts
- cypress/plugins/index.js
- cypress/tsconfig.json
- src/components/LanguageSwitcher/index.tsx
- src/components/Main/Results/ResultsCard.tsx
- src/langs.ts
Contributes to #19 
Add e2e tests for the language switcher
> feat: add e2e test for language switcher

- src/algorithms/model.ts
Addressing the easiest linting wins in `model.ts`.
None.
> Some more linting easy wins for #101 in model.ts

- .nowignore
- now.json
- Contributes to #21 
Fix 404 errors on non-root route on now.sh deployments
Infra, CI
That's what I am doing here :)
> fix(ci): setup proper rewrites on now.sh

- src/assets/text/faq.md
Adds additional FAQs
Address recurring questions by users
FAQ page
none -- check rendering.
> cherry-pick additional faqs

- src/components/Main/Main.tsx
Fixes #200 
This PR updates the debounced autorunning of the scenario, when checked, to ensure that autorun is triggered on severity table changes.
Scenario autorun.
Ensure autorun is checked on the results card, and modify table values under the scenario severity.  Observe that the scenario autoruns showing the updated results.
> Autorun scenario on severity change

- src/components/Main/Results/OutcomeRatesTable.tsx
Fixes #229 
It was a math error
Outcome rates testing
Shouldn't be affected.
> fixed erroneous subtraction of critical

- src/components/Main/Results/DeterministicLinePlot.tsx
Contributes to #234 
Make tooltip positioning in results chart smoother when mouse is moved over graph.
New throttleDelay value added in ComposedChart component in src/components/Main/Results/DeterministicLinePlot.tsx
Move mouse over tooltips in graph and see if desired smoothness is achieved.
> Jittery chart fix

- src/assets/data/scenarios/containment.ts
- src/assets/data/scenarios/epidemiological.ts
- src/assets/data/scenarios/overall.ts
- src/assets/data/scenarios/simulation.ts
`eslint --fix` for `src/assets/data`.
None.
> #101: eslint --fix assets/data

- src/algorithms/model.ts
- src/algorithms/run.ts
- src/algorithms/utils/TimeSeries.ts
- src/algorithms/utils/exportResult.ts
`eslint --fix` for `src/algorithms`.
None.
> #101: eslint --fix algorithms

- src/components/Main/Scenario/ScenarioCardContainment.tsx
- src/components/Main/Scenario/ScenarioCardEpidemiological.tsx
- src/components/Main/Scenario/SeverityTable.tsx
`eslint --fix` for `src/components/Main/Scenario`.
None.
> #101: eslint --fix components/Main/Scenario

- src/components/Main/Containment/ContainmentGraph.tsx
- src/components/Main/Disclaimer.tsx
- src/components/Main/state/reducer.ts
`eslint --fix` for some of `src/components/Main`.
None.
> #101: eslint --fix components/Main

- babel.config.js
- config/webpack/lib/webpackTsChecker.ts
- config/webpack/webpack.client.babel.ts
`eslint --fix` for some of `src/components/Main`.
None.
> #101: eslint --fix config

- src/components/Main/Results/AgeBarChart.tsx
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/ResultsCard.tsx
`eslint --fix` for `src/components/Main/Results`.
None.
> #101: eslint --fix components/Main/Results

- README.md
Updating README.md (as per conversation on Spectrum)
#217 
-Added /src directory structure - wasn't quite sure of all of the contents use so leaving that for people with more knowledge
-Added new contributor guide with guide for installing node.js and yarn globally, and general open source workflow
README.md
N/A
> README directory structure & new contributor guide

- src/algorithms/model.ts
- src/state/ui/ui.reducer.ts
`eslint --fix` as there are some new changes that are not compliant.
None.
> #101: eslint --fix again

- src/components/Form/FormHelpButton.scss
- src/components/LandingPage/LandingPage.scss
- src/components/Main/Results/DeterministicLinePlot.scss
- src/components/Main/Results/ResultsCard.scss
- src/components/Main/Scenario/SeverityTable.scss
- src/pages/Loading.scss
- src/styles/global.scss
`stylelint --fix` applied.
None.
Build, test, run & play around.
> #101: stylelint --fix

- src/algorithms/model.ts
- src/components/Main/Main.tsx
- src/types/jpg-module.d.ts
More manual `tsc` error fixes in `model.ts` and `Main.tsx`.
None.
> #101: more tsc fixes

- .gitignore
- src/components/LandingPage/LandingPage.tsx
- src/helpers/localStorage.ts
- src/state/ui/ui.reducer.ts
#215 
- 
I really curious about consistency and I want to align with maintainer. If this PR is ok, I can go further and implement StorageService which is an abstraction and can be used upon any type of storage.
Storage
1) if something is wrong, I can easily fix it
2) I made a small PR to understand the policy, how interesting it is for you to have consistency
3) checkout description section, I will be pleased to implement storage service
4) In addition, I refactored some things in my OL that could lead to errors in the future.
> Refactor local storage

- src/assets/text/faq.md
- Fixes #285 
Small typo fix.
Fixes typos in the FAQ.
I ran it locally, there are no tests for the markup of the FAQ.
> Fix typos in FAQ

- package.json
- src/assets/data/validation/schemas/case_counts.schema.json
- src/assets/data/validation/schemas/country_age_distribution.schema.json
- src/assets/data/validation/schemas/populations.schema.json
- src/assets/data/validation/validateSchema.test.ts
- yarn.lock
- Contributes to #283
- added some json schemas using jsonschema.net inferring from existing data
- write unit tests to validate against them
- assets/data
- yarn test
> Add jsonschema for data, write unit tests to validate data against json schemas

- src/components/Main/Results/DeterministicLinePlot.tsx
Issue #312 
Explicitly looks for log(x<=0) numbers being sent to our plotting functions.
DeterministicLinePlot
None that I'm aware.
> Positive number verification for line plot

- src/algorithms/model.ts
- src/algorithms/run.ts
- src/components/Main/Results/DeterministicLinePlot.tsx
The integration of the ODE should be more accurate.
None
Changed the step size/day. Removed hard-coded instances of this assumption.
The ODE integration and the line plot which assumed a 4 times/day sampling.
Performance could be impacted. Please test.
> Lowered euler step size

- src/components/Main/Main.tsx
- fixes #311 
allow "Confirmed cases" to be "None"
Plot will not display any empirical data if "Confirmed cases" is set to "None"
Modify "Confirmed cases" between "None" and some other value
> allow confirmed cases to be "none"

- data/parsers/france.py
Due to a conflict the merge of PR#76 in the archived data repo was not correct. This is the correct fix.
> Fix France parser according to PR#76 in archived data repo

- data/Pipfile
- data/Pipfile.lock
- data/README.md
Issue #342.
Provide a pipenv environment to contributors and ensure uniform build settings.
All python scripts within the data directory.
Please check that the environment works on other computers.
> Provide Pipenv environment for data contributors

- src/components/LandingPage/LandingPage.tsx
- src/pages/ErrorPage.tsx
N/A
- 
came across this issue, so just translate all these strings
landing page
error page
> translate strings in landing page and error page

- .eslintignore
- .prettierignore
- README.md
- data/README.md
- src/assets/text/faq.md
Since https://github.com/neherlab/covid19_scenarios_data is no longer in use I adjusted the docs
Docs
> Emphasize unified app and data repository in docs

- src/components/Buttons/LinkButton.tsx
- https://github.com/neherlab/covid19_scenarios/pull/368
- https://github.com/neherlab/covid19_scenarios/pull/368#issuecomment-608978833
Fixing the warnings introduced with https://github.com/neherlab/covid19_scenarios/pull/368:
> fix: Fixing React warnings

- src/components/LandingPage/LandingPage.scss
- src/components/LandingPage/LandingPage.tsx
Contributes to #384 
Added style to "skip landing page" checkbox on landing page using CSS and pseudo-elements. NOTE: Checkbox may not be fully functional.
LandingPage.tsx and LandingPage.scss files in src/components/LandingPage/
> Skip landing page checkbox style

- tools/convertSchemasToTypes.ts
JSONSchemaStore is an abstract class, its fetch method needs to be
defined.
I've defined it in a Store class, so using new Store() is not
instanciating an abstract class anymore.
Also, with this change, we can now cross-reference things between
different schema files.
-
> added custom JSONSchemaStore fetch

- src/components/Main/Main.tsx
- src/components/Main/Scenario/ScenarioCard.tsx
- src/components/Main/Scenario/ScenarioCardContainment.tsx
- src/components/Main/Scenario/ScenarioCardEpidemiological.tsx
- src/components/Main/Scenario/ScenarioCardPopulation.tsx
For #382 
Relates to #432 #412 #403 
~~Note: This is a WIP. It is how Formik could/should be used. But still may not fix the underlying performance issues due to other bugs etc.~~
Use formik in a less controlled manner.
Mitigation Table
Add/Remove from the mitigation table.
> Use formik values to render the mitigation table

- schemas/CountryAgeDistribution.yml
there were several typos in the file :
* minimim instead of minimum
* we don't want a maximum since it's not in percent
* the properties name didn't match so validation was actually not
effective.
> fix: countryAgeDistribution schema

- data/populationData.tsv
Contributes to data on beds and ICU beds for Oz and Kiwi in the `data/populationData.tsv` file.
> Totals for Australia and New Zealand

- data/sources.json
This PR updates ``israel`` data source with license information
``/Data``
No need
> Updated israel source license

- src/assets/text/faq.md
- src/assets/text/updates.md
- src/pages/About.mdx
None
Updates the About, FAQ, and Updates pages to reflect that scenarios now contain a few selected "fitted" parameters.
About page
Updates page
FAQ page
Grammar?
> updated the pages to reflect the fact that data is now fit to

- src/components/Form/HelpLabel.tsx
- src/components/Layout/NavigationBar.scss
- src/components/Layout/NavigationBar.tsx
- src/components/Main/Disclaimer.scss
- src/components/Main/Disclaimer.tsx
- src/components/Main/Scenario/SeverityCard.tsx
- src/styles/global.scss
- Fixes #444
- Contributes to #71 
- General improvement in layout
- FTitle for" Age-specific" card now fits the screen
- Navbar items are now scrollable if don't fit
- Unrelated, but affs some dashes between words
> Fix mobile layout

- data/parsers/france.py
Columns in the sources changed. This corrects the columns for the new format.
> Fix France parser to account for source format change

- src/pages/Loading.scss
- https://github.com/neherlab/covid19_scenarios/issues/442
- https://github.com/neherlab/covid19_scenarios/pull/465
> fix: #442 Spinner is not centered

- src/components/Main/Results/DeterministicLinePlot.tsx
Fix broken plots when changing tMin.
plots
change tMin, see whether all data show.
> allow for intra day variation in time points

- .travis.yml
- codecov.yml
- config/jest/jest.config.js
- package.json
- yarn.lock
- Contributes to #21 
Simply sets up codecov.io tool for test coverage reports
> feat: setup codecov

- .codeclimate.yml
- .travis.yml
- docker/docker-compose.codeclimate.yml
- package.json
- Contributes to #21 
Configures codeclimate.com tools
> feat: add codeclimate

- data/populationData.tsv
Add Ukraine to the list of countries
Should add Ukraine to the list of scenarios
Open the dropdown, find Ukraine in the list
> Ukrainian population data

- .nowignore
> fix: fix build on now.sh due to an ignored required file

- src/components/Main/state/serialization/DtoConverter.test.ts
- src/components/Main/state/serialization/StateSerializer.test.ts
- src/components/Main/state/serialization/URLSerializer.test.ts
- Fixes some tsc bugs in #512 
To fix tsc errors in the state serialization tests
- DtoConverter.test.ts
- StateSerializer.test.ts
- URLSerializer.test.ts
`yarn test`
> Fixed tsc errors in tests

- src/components/Main/PrintPage/PrintPage.tsx
#488 
Increase readibility and information content of the print page. 
print page
render print page.
> minor edits to print page

- package.json
- src/components/Form/CardWithoutDropdown.tsx
- src/components/Form/FormHelpButton.test.tsx
- src/components/Form/FormHelpButton.tsx
- src/components/Form/HelpLabel.tsx
- src/components/Layout/ColCustom.tsx
- src/components/Main/Main.scss
- src/components/Main/Main.tsx
- src/components/Main/Results/AgeBarChart.tsx
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/ResultsCard.tsx
- src/components/Main/Scenario/ScenarioCard.tsx
- src/components/Main/Scenario/ScenarioCardEpidemiological.tsx
- src/components/Main/Scenario/ScenarioCardPopulation.tsx
- src/styles/bootstrap-variables.scss
- src/styles/bootstrap.scss
- yarn.lock
- #284 
Implements expansion of the Result card, similar to Youtube player's theater mode.
Results card
> Feat: expand results card

- src/algorithms/results.ts
- src/algorithms/run.ts
- src/algorithms/types/Result.types.ts
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/MitigationLinePlot.tsx
- src/components/Main/Results/R0LinePlot.tsx
Plot the resulting R0 along with the uncertainty and mitigations. 
Need to sort out the joint display of mitigations and R0
types, plots, run
> add R0 to the mitigation plot

- data/parsers/france.py
Update France parser to account for new change in format in input database.
> Update France parser following input format change

- src/algorithms/run.ts
- src/algorithms/types/Result.types.ts
- src/components/Form/FormRangeSlider.tsx
- src/components/Main/Mitigation/MitigationTable.tsx
Fixes the various problems with the sliders, both in style and performance, introduced by PR #537 
Right now the slider and its usage feels sluggish and the form needs to be harmonized with the rest of the app. This pull request is an attempt to fix both problems.
components/Form/FormRangeSlider.tsx
components/Main/Results/*
Slide values around.
> [1.2] Fix slider performance and styles

- config/webpack/webpack.client.babel.ts
- package.json
- yarn.lock
> fix: now.sh build failure

- src/algorithms/utils/exportResult.ts
- src/components/Main/Results/ExportSimulationDialog.tsx
Contributes to #512
Fix lint errors & fix export all
Clean linting and Export All 
Export result & Export all
> Fix lint errors in ExportDialog

- package.json
- src/components/Faq/FaqTableOfContents.tsx
- src/components/Main/state/serialization/URLSerializer.test.ts
- src/types/jsurl.d.ts
- yarn.lock
Contributes to #512
Fix some `yarn tsc` errors:
- jsurl type was for a different package
- check possibly undefined
- use latest r0 & mitigationValue types
Lintiness
Check FAQ TOC is still there.
> Misc lint fixes

- data/parsers/france.py
- data/parsers/utils.py
Add regional data, which is more detailed (ICU, hospitalized, etc), to obtain country data for France
add_cases in utils.py needed change since data for France is irregular, so a check for None values was done
france.py was modified to add regional data
> Add (sum up) regional data to obtain country data for France

- src/components/Main/Disclaimer.tsx
- src/components/Main/Results/ResultsCard.scss
Contributes to #577 
IE support.
Checked that the changes did not cause a regression with other browsers.
> Fix two IE11 button styling issues

- data/scripts/scenarios.py
- src/assets/data/case_counts.json
- src/assets/data/scenarios/scenarios.json
Simple fix of the export of scenario growth rates to only keep one significant figure.
scenarios.py
Look at the exported data.
> Round of lower/upper bounds on R0 & mitigation efforts

- config/webpack/webpack.client.babel.ts
https://vercel.com/blog/zeit-is-now-vercel
-
> fix: rename "now" to "vercel"

- src/algorithms/model.ts
- src/algorithms/results.ts
- src/algorithms/run.ts
- src/algorithms/types/Result.types.ts
- src/components/Main/PrintPage/TableResult.tsx
- src/components/Main/Results/AgeBarChart.tsx
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/ExportSimulationDialog.tsx
- src/components/Main/Results/LinePlotTooltip.tsx
- src/components/Main/Results/OutcomeRatesTable.tsx
- src/components/Main/Results/ResponsiveTooltipContent.tsx
- yarn.lock
- 
The geometric mean and standard deviation led to odd visual results. 
We now will report percentiles over time.
model.ts
run.ts
Changed userResult.trajectory.mean -> userResult.trajectory.middle
Check model plots and exports with new data structure.
> Change model results to percentiles over geometric mean/standard deviation

- src/components/Main/PrintPage/PrintPage.tsx
- src/components/Main/PrintPage/TableResult.tsx
- src/components/Main/Results/AgeBarChart.tsx
- src/components/Main/Results/ChartTooltip.tsx
- src/components/Main/Results/OutcomeRatesTable.tsx
- src/components/Main/Scenario/ScenarioCardContainment.tsx
Milestone 1.2
Age stratified bar chart needed some love after all the changes.
AgeBarChart.tsx
ChartTooltip.tsx
Open up, run and look at results.
> [Fix] Update the age stratified chart to have error bars

- src/components/Main/Results/ChartTooltip.tsx
> fix: fix type errors in chart tooltip

- src/components/Main/state/serialization/v2.0.0/serialize.ts
- 
Adds manual validation for age groups - quantity and consistency
> feat: validate age groups

- src/components/Main/PrintPage/PrintPage.tsx
- 
Fixes crash on print preview page due to type mismatch following the update of schemas.
> fix: crash on print preview page

- src/components/Main/state/serialization/v2.0.0/serialize.ts
- 
Fixes user-friendly error messages having the developer's information
> fix: fix age group validation error messages

- src/algorithms/utils/exportResult.ts
- src/components/Main/Results/ExportSimulationDialog.tsx
- 
This aligns the filenames text in the export window with the actual filenames of downloaded files
> fix: adjust export filename text

- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/Utils.test.ts
- src/components/Main/Results/Utils.ts
Related to [this Fixme](https://github.com/neherlab/covid19_scenarios/blob/1a382d629a300b549f6b5559378921b0f80bc191/src/components/Main/Results/DeterministicLinePlot.tsx#L107), an incremental refactoring of the DeterministicLinePlot component.
(Additional context: #636)
Reduce the code complexity of `DeterministicLinePlot.tsx` by extracting the `verifyPositive()` and `verifyTuple()` methods into a utility module. Also narrows the type definition of `verifyTuple`'s params and return value. Also adds units tests for those methods, to aid future refactoring. 
Slight reorganization of the code. Adds more unit tests.
This PR adds units tests for `verifyPositive()` and `verifyTuple()` methods.
`yarn test`
> Refactor verifyPositive and verifyTuple functions into a Utils module.

- now.json
- vercel.json
Reverts neherlab/covid19_scenarios#674
> Revert "refactor: move environment variables to Vercel's UI"

- src/components/Main/Scenario/ConfirmedCasesDataPicker.tsx
- 
This disables case counts upload for the next release. More work has to be done until it is in releasable state.
> fix: disable case counts upload

- docker/docker-compose.data.yml
- docker/docker-compose.dev.yml
> chore: add custom docker networks to avoid collisions

- data/parsers/singapore.py
- data/sources.json
Added singapore.py parser to provide daily case count data for Singapore and updated sources.json.
> Covid19 Singapore Data

- src/styles/_variables.scss
> feat: reduce opacity of the results overlay when running

- data/scripts/scenarios.py
- src/assets/data/scenarios.json
Ensures that the generated `scenario.json` file is formatted and sorted in all cases. This way the changes can be easily `diff`'ed visually.
Data generation
> feat: generate formatted json

- src/algorithms/__test_data__/getPopulationParams.input.default.ts
- src/algorithms/types/convert.ts
- src/components/Main/Scenario/ScenarioCardContainment.tsx
> fix: resolve some of the type errors

- package.json
- src/components/Main/Results/OutcomeRatesTable.tsx
- yarn.lock
Fixes #686 
This PR replaces the Proportions section of the Outcomes Card with a Pie Chart using the color codes established by other components
Outcomes Card
> Showing more love to the outcomes card

- src/components/Main/PrintPreview/PrintPreview.tsx
- Related to #488 
Fixed some of the existing short descriptions as well as adding a few longer descriptions in the form of footnotes. Copied long descriptions from homepage help text as to not cause any translation issues. Are there other notes or descriptions that need to be added? And is the footnote style the direction you want to go, or would another format be better? 
PrintPreview.tsx
> Additional PDF Details

- data/parsers/brazil.py
- Resolves #345 
brazil.io updated their URLs and they now compress the files.
This PR adjusts our parser for that.
Sorry for the large diff, my text editor formats files automatically and I did not bother to undo.
> fix: adjust Brazilian parser for the new upstream file format

- data/generate_data.py
- data/parsers/spain.py
This adds printing errors to console, as well as some spacing for clarity
> feat: improve parser logs

- src/components/Main/Scenario/ScenarioCardPopulation.tsx
This fixes label for "Custom" country being undefined due to incorrect usage of i18next library
> fix: ensure dropdown option labels are correct

- src/i18n/i18n.ts
Contributes to  #56 
Adds more languages for localization.
> feat: add more languages

- config/next/next.config.ts
- config/next/withMdx.ts
- package.json
- src/types/remark-rehype.d.ts
- yarn.lock
This 
- fixes the problem where Tex math was not rendered properly
- makes double and triple hyphens to be rendered as dashes
> feat: render math, render double and triple hyphens as dashes

- src/components/Layout/NavigationBar.tsx
> fix github link from header
