- src/algorithms/Param.types.ts
- src/components/Main/Results/DeterministicLinePlot.tsx
This adds people currently hospitalized for COVID to the graph (where available). This is useful to compare the current situation to the model, but the plot gets a little cramped.
> add hospitalized to empiricalDatum and show in plot

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Contributes to https://github.com/neherlab/covid19_scenarios/issues/16.
The following templates are added:
- Issue templates: template for bug reports and configuration allowing the creation of blank issues ([github docs](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository))
- Basic PR template
- Basic contribution guidelines
- Code of Conduct: https://www.contributor-covenant.org/
> Added open source contrib templates

- src/algorithms/run.test.tsx
This PR is part of a larger issue, described by #19.
It addresses a specific test named "should work for a lot of countries". It was failing because it used the wrong Country Name key to look up Population Scenario and Country Age Distribution. The failure was masked because the test was wrapped in a try/catch.
This PR fixes the test and removes try/catch.
> #19 Fix silent failure of 'should work for a lot of countries'.

- src/components/Form/CollapsibleCard.tsx
Not a big change but its the first thing I realized when running the project, the console complained about html validation as <button> can not contain <button> inside.
This PR solves that while keeping the same design and functionality at the CollapsibleCard CardHeader
> Prevent having button inside button on CollapsibleCard-CardHeader

- src/components/Main/Containment/ContainmentGraph.tsx
Fixes the y-axis text overlapping issue for mobile devices. 
Fixes https://github.com/neherlab/covid19_scenarios/issues/78
Contributes to https://github.com/neherlab/covid19_scenarios/issues/71
This creates a 4 / 5 mobile ratio inside the containmentGraph component. A  ternary operator is implemented to handle the ratio swtich
> added aspect ratio and conditon for mobile layout in mitgation graph

- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
- README.md
This adds the Spectrum chat link to the new issue templates choose page and CONTRIBUTING.md file.
- Contributes to #16
> Add spectrum chat link

- src/components/LanguageSwitcher/index.tsx
There was a warning in the console about a missing `key` in the DropdownItem component
> Fix missing key

- config/webpack/webpack.client.babel.ts
This PR addresses [this comment](https://github.com/neherlab/covid19_scenarios/issues/72#issuecomment-602071478) and allows for the proper generation of sourcemaps for an improved debugger experience in `development` mode (it's actually `!= production` because I thought this would be more future proof), which I found really useful for myself.
> Allow for browser sourcemaps when in dev mode

- src/components/Main/Results/DeterministicLinePlot.tsx
This PR simply addresses the `Warning: Each child in a list should have a unique "key" prop.` that are caused by the `<Line />` and `<Scatter />` lists in `DeterministicLinePlot`
> [housekeeping] Fix list child key props in DeterministicLinePlot

- src/components/Main/Containment/ContainmentGraph.tsx
Previously the graph was being re-rendered on every
event, which caused problems when trying to drag a
graph vertex at the same time as de-focussing another
input element.
Now the graph is only rendered initially, and then when
either the graph data changes, or the graph is resized.
Fixes #72
> fix: do not re-render Mitigration graph unnecessarily

- src/components/Form/FormDatePicker.tsx
Fixed the logic that decided the number of months that had to be rendered on mobile. Previously it was rendering 4. We have space only to render 1.
https://github.com/neherlab/covid19_scenarios/issues/71
Date Picker
> Fix Calendar Alignment on Mobile

- src/components/Main/Results/DeterministicLinePlot.tsx
This PR simply fixes the type error created by the `interface LineProps`' `legendType` conflicting with `rechart`'s `LineProps`' expected `legendType`s, which are comprised more specifically of string literals
> [housekeeping] Fix LineProps['legendType'] type-safety with <Line />

- src/components/Form/FormSpinBox.tsx
- src/components/Main/Containment/ContainmentGraph.tsx
- src/components/Main/Scenario/ScenarioCardContainment.tsx
If you go onto the "Transmission rel to baseline" graph, and type an "invalid" number (ie below 2), the whole page crashes. This stops the page from crashing.
If you enter a number too high (10,000), the page also crashes. This throws a warning in that scenario once the numbers get higher than 100, but doesn't stop user behavior. (Would be nice!)
I probably won't get to it into this diff, but if you bring the number to 1 and then back to 10, the y values of the graph are lost seemingly until you refresh. I don't really know why this is.
None
Just that one graph, as far as I know!
Manual.
N/A
> Fix crash when inputing number below 2 on ContainmentGraph

- src/components/Main/state/URLSerializer.ts
Fix `AllParams` import path and convert to type import in `URLSerializer`
https://github.com/neherlab/covid19_scenarios/issues/101
> fix AllParams import path and convert to type import in URLSerializer

- src/components/Form/HelpLabel.tsx
Hello, I noticed that the ? icon was slightly misaligned with the form label so I decided to take a look.
The header of the different sections and the form fields
I compared how it looks in mobile and desktop viewports and it looks good
> fix(form): make form help button align with input label

- src/components/Main/Main.tsx
- src/components/Main/Results/ResultsCard.tsx
- src/helpers/hooks.ts
This PR addresses the "Tapping 'Run' button gives no clue that there is more content appeared below" task in https://github.com/neherlab/covid19_scenarios/issues/71. Specifically, it uses a `div` wrapper around `ResultsCard` (I would've preferred to use the `Col` that already wrapped it, but getting a `ref` out of reactstrap components proved too difficult) to [`scrollIntoView(alignToTop)`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).
It also:
- ensures that the auto-scrolling is only triggered when on a mobile layout wherein the form layout is constrained to a single column
- attempts to use [`scroll-behavior: smooth`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) (even though it isn't supported in Safari or IE, but it's better than …
> Scroll ResultsCard into view when "Run" is tapped

- src/components/Main/Results/DeterministicLinePlot.tsx
fix DeterministicLinePlot YAxis scale type-error
https://github.com/neherlab/covid19_scenarios/issues/101
> fix DeterministicLinePlot YAxis scale type-error

- package.json
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/i18n.ts
- src/locales/en/index.ts
- src/locales/localized/localized.json
- yarn.lock
- Add localizedNumber to languages
- Format DeterministicLinePlot according to project style guide
- Format labels on Y axis 
- Contributes to https://github.com/neherlab/covid19_scenarios/issues/101
- Contributes to https://github.com/neherlab/covid19_scenarios/issues/83
- Contributes to https://github.com/neherlab/covid19_scenarios/issues/56
It is also now possible to format any number according to the locale of the selected language, eg: `t('localized:number', { value: 1000 })`
This is applied to the numbers on the Y Axis of the graph
> Add localizedNumber, format labels on Y Axis of DeterministicLinePlot

- src/components/Main/Main.tsx
- src/components/Main/Results/DeterministicLinePlot.tsx
- Fix the various type errors in `src/components/Main/Results/DeterministicLinePlot.tsx` by making the variables' types statically inferrable (accomplished with immutability). The logic is still the same though!
- [Type-only `import`s](https://github.com/neherlab/covid19_scenarios/blob/master/src/components/Main/Results/DeterministicLinePlot.tsx#L4) weren't [introduced to TypeScript until 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export), so I had to [upgrade Prettier to 2.0.1](https://prettier.io/blog/2020/03/21/2.0.0.html#typescript-38-7631httpsgithubcomprettierprettierpull7631-by-thorn0httpsgithubcomthorn0-7764httpsgithubcomprettierprettierpull7764-by-sosukesuzukihttpsgithubcomsosukesuzuki-7804httpsgithubcomprettierprettier …
> Fix DeterministicLinePlot.tsx type errors and upgrade Prettier to 2.0.1

- src/components/Form/FormHelpButton.tsx
I believe this fixes #134. 
It seems there is no support for focus on button in safari:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus
> I134 fix for safari help

- src/components/Main/Results/AgeBarChart.tsx
`react-i18next`'s translation function (`useTranslation().t`) returns `TFunctionResult` (i.e. `string | object | Array<string | object> | undefined | null`), but `rechart`'s components only accept `string | number | undefined` for their `name`s, `label`s, .etc, so extend `TFunction` with a signature that returns _just_ `string | number | undefined`
https://github.com/neherlab/covid19_scenarios/issues/101
> fix AgeBarChart type errors

- src/components/Main/Results/DeterministicLinePlot.scss
- src/components/Main/Results/DeterministicLinePlot.tsx
Add the ability to toggle visibility of chart elements by clicking the legend.
Legend elements now show with hand cursor to indicate interactivity.  Clicking will toggle visibility of line/scatter, and legend text will show with dark-grey color and strikethrough when disabled.
Add the ability to toggle rendering of lines/scatters on the result chart.
- Fixes https://github.com/neherlab/covid19_scenarios/issues/132
DeterministicLinePlot.tsx
Pull branch, run simulation, observe hand cursor over legend labels, clicking legend label toggles visibility of the chart data, and legend label shows with dark-grey color and strike-through when disabled.
> Make chart lines/scatters toggleable

- src/components/Form/FormHelpButton.test.tsx
- src/components/Form/FormHelpButton.tsx
Help information would not display for Safari users.
Fixes https://github.com/neherlab/covid19_scenarios/issues/134
Help Popovers.
- Tested with Chrome & Safari on MacOS
- Changed the help popover unit test to use clicks
None
> issue #134: use an UncontrolledPopover to fix popovers for Safari

- src/algorithms/test/run.test.tsx
This PR fixes the most offensive (but not all) lint warnings in `run.tests.tsx`.
- Removes unused variable assignments.
- Replaces the loop statement with a map() construct.
- Fixes Prettier style warnings.
#101 
Unit tests and linting.
`yarn test:lint src/algorithms/test/run.test.tsx`
> #101/Fix obvious lint warnings in run.tests.tsx

- src/components/Main/Disclaimer.tsx
- src/pages/Home.tsx
Add disclaimer modal dialog which shows by default.
Disclaimer contains basic MIT software disclaimer, plus responsible use request, and GDPR local storage disclosure.
Disclaimer has "don't show me again" checkbox, which will suppress future showing on the same device, unless the disclaimer version number is increased.
- Fixes https://github.com/neherlab/covid19_scenarios/issues/25
Disclaimer which will show on mount of main simulation page, '/'
Pull branch, observe that dialog shows on mount of simulation main page with disclaimer content.  Disclaimer will show on all subsequent loads of the page, unless 'Don't ask me again' was checked when the disclaimer was dismissed, in which case, it won't show again unless localstorage is cleared, or disclaimer version is bumped.
> Add disclaimer to the home page

- src/algorithms/test/TimeSeries.test.ts
DRY a comparison logic in TimeSeries.test.ts to address a warning generated by rule:
`tslint:no-identical-functions`
#101 
Unit tests, specifically `TimeSeries.test.ts`
`yarn test:lint`
> #101/DRY TimeSeries comparison logic

- src/components/Main/Results/DeterministicLinePlot.tsx
fix problem with wrong key in plot-data set up. That said, or nomenclature regarding `dead` `death` and `deaths` is for from ideal. 
Only affects the data aggregation for the plot.
> fix key for death count in plot set-up

- src/algorithms/test/run.test.tsx
This fixes a type warning in the `run.test.tsx` unit test:
_"Unexpected any. Specify a different type"_.
The fix is trivial, because the  appropriate type is already defined in:
`src/assets/CountryAgeDistribution.types.ts`
#101 
Unit tests.
`yarn test:lint`
> #101/Use existing CountryAgeDistribution type in unit test.

- tsconfig.json
This fix addresses a specific class of type errors in the unit tests. Both Jest and Chai (a Cypress dependency) declare a global "Assertion" type. Under certain conditions the Chai version takes precedence, resulting in the type error. For example: 
`error TS2339: Property 'toBeObject' does not exist on type 'Assertion'.`
This fix works by excluding the cypress/ folder from `tsconfig.json`, thereby keeping the unnecessary Chai definitions out of the global namespace.
#101 
Unit tests.
`yarn test:lint`
> #101/Fix type conflict caused by global exports of Chai, a Cypress dependency.

- src/components/Main/Main.tsx
- src/components/Main/Results/ResultsCard.tsx
When the scenario form is interacted with the entire wrapped <Formik> is re-rendered. There is a sluggishness that is especially noticeable when the run results are displayed. This change causes the ResultsCard to only re-render when a prop shallowly changes via React.memo. 
Note: The only change in this diff that matters is the `React.memo` export. The rest are auto-save prettier lint fixes.
Related to https://github.com/neherlab/covid19_scenarios/issues/17
Form performance.
Run. Then interact with the form. It should be reasonably performant.
> performance: only render results if they shallowly change

- src/algorithms/test/run.test.tsx
The country name label "United States" has been changed to "United States of America", but the field was not updates in the unit test. This PR addresses that fragility. With this PR we simply run all the population scenarios. It measures the same functionality, but removes the need to sync data labels in the unit test.
The breaking change was introduced in 5594f13007f9f95b854a8a60efb0af0dc314dd42
Unit tests.
`yarn test:lint src/algorithms/test/run.test.tsx`
> test: Fix regression failure in algorithms/test/run.test.tsx

- src/algorithms/test/TimeSeries.test.ts
This PR results in a completely linted `src/algorithm/tests/TimeSeries.test.ts`.
#101 
Unit tests and linters.
`yarn test:lint TimeSeries`
> #101/Final linter fixes for TimeSeries tests. Removes "no-duplicate-string" warnings.

- src/components/Main/Main.tsx
This fixes a type error in `Main.tsx`.
It casts the `assets/data/country_age_distribution.json` import as a `CountryAgeDistribution`. 
#101 
`yarn tsc`
> #101/Cast countryAgeDistribution json as CountryAgeDistribution type.

- src/algorithms/test-data/ageDistribution.small.example.ts
The file [`src/algorithms/test-data/ageDistribution.small.example.ts`](/neherlab/covid19_scenarios/tree/master/src/algorithms/test-data/ageDistribution.small.example.ts) exports a data structure typed as `CountryAgeDistribution`, but the linter warns that it does not match the shape. This PR removes the type assignment.
(The file doesn't appear to be used anymore – should it be deleted?)
#101 
Unknown
`yarn test:lint`
> #101/Remove the CountryAgeDistribution type from incompatible shape.

- cypress/integration/navigation.spec.ts
- cypress/integration/results.spec.ts
- cypress/support/commands.js
- cypress/support/index.d.ts
With the introduction of i18n, the navigation bar now gets his content from the i18next. On the test, the content is now undefined because at the time we get the content of the links the translation is not made. This is not necessary since we only care about the link url being correct.
- update the test to rely on the url
Second issue is the introduction of the disclaimer popup, it breaks the tests because the area we ry to interact with are below the modal's overlay.
- add a command to close the popup automatically
- Contributes to #19 
run `yarn e2e` or `yarn e2e:dev`
> fix: add a command to close the disclaimer on each pages, update navigation test to not rely on language

- src/components/Main/Results/AgeBarChart.tsx
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/OutcomeRatesTable.tsx
- src/components/Main/Results/ResultsCard.tsx
- src/locales/en/translation.json
Add humanization of numerical results in the results card.
Added a toggle to enable/disable humanized results (on by default).
- Fixes https://github.com/neherlab/covid19_scenarios/issues/158
Results card data values, line graph, bar charts, and overview of results table
Run simulation, ensure "Show humanized results" is enabled.  Hover over graphs and observe that results show in human friendly format, i.e 1.25 M, rather than 1250000.  Observe that tabular results, and axis also show human friendly values.
> Add humanization of numerical values

- src/components/Main/Results/AgeBarChart.tsx
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/OutcomeRatesTable.tsx
- src/helpers/numberFormat.ts
- src/types/Intl.d.ts
Fixes #198 
- Always internationalize numbers
- Optionally 'humanize' them
- Keep the total number rounding in the outcomes table when numbers are non humanized
Number display
Check numbers on axis and tooltips.
@rcbevans can you check this? Thanks!
> internationalize number display

- src/components/Main/Results/DeterministicLinePlot.tsx
Fixes #199 -- problem was that the scale keyword for plots was translated. 
- 
make plots on log scale show in all languages.
results plot.
only affects rendering out output.
> this fixes the plots in different language

- src/components/Main/Main.tsx
Contributes to #101 
The tsc compiler complains about a missing `countryAgeDistribution` type. The correct type is `countryAgeDistributionData`. Also, to keep with this convention of appending "Data" to imported JSON data modules – `countryCaseCount` is renamed to `countryCaseCountData`.
Linting of Main.tsx
`yarn tsc` should no longer complain about the type problem.
> #101/Fix the misnamed key type in isCountry() function.

- src/algorithms/test/TimeSeries.test.ts
- src/algorithms/test/__snapshots__/TimeSeries.test.ts.snap
#194 
The `TimeSeries.test.ts` test _'interpolation within the timerange occurs as expected'_ fails sometimes on some machines. The test uses a snapshot to compare floating point values. This PR extracts the expected values from the snapshot, inlines them into the test, and compares them to the results using Jest's .isCloseTo() assertion.
TimeSeries unit tests.
`yarn test:lint TimeSeries`
> testing/Compare interpolated values using isCloseTo() instead of snapshot.

- src/algorithms/model.ts
- src/algorithms/types/Result.types.ts
Fix the type of `sub` args in `update`, `updateAt` and `push` functions of `model`, reducing `tsc` errors.
None.
> #101: Fix model arg types in model update functions

- src/index.ejs
Contributes to #106 
This PR adds the missing meta tag "description" to the HTML, that's a improvement for SEO based on the lighthouse audit report:
`src/index.ejs`
Open the browser, run a report using lighthouse with SEO option marked.
> Add description meta tag

- config/.prettierrc
#101 , #260 
The linter is configured to want parens around arrow function parameters, but Prettier was not configured to add them. Consequently there are regressions like #260. This PR fixes that.
Linting
Edit a source file. Try to create an arrow function without parenthesized parameters. Your editor should automatically add the parentheses.
> #101/Add "arrowParens": "always" to prettier config.

- src/components/Main/Results/AgeBarChart.tsx
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/ResponsiveTooltipContent.scss
- src/components/Main/Results/ResponsiveTooltipContent.tsx
- src/components/Main/Results/chartHelper.ts
- src/styles/global.scss
All right, here's a fixed PR discussed here: [#157](https://github.com/neherlab/covid19_scenarios/pull/157)
There was some weirdness with rebasing. So this PR should only deal with my changes, which include:
- Custom ResponsiveTooltipContent component, which will divide in two columns on mobile for better readability.
- Repositioning of the chart Tooltip component when in single column mode.
- When clicking on chart in single column mode, the page scrolls the chart to top, so that repositioned Tooltip is wholly visible.
@ivan-aksamentov if you're happy with this you can merge.
> Feat: Responsive tooltips

- .travis.yml
Contributes to #101
There are currently 114 eslint warnings. With this change future PRs will not be able to increase that count. The goal would be to gradually reduce this high water number as lint errors are fixed until an eslint warning free codebase is reached 🎉 
Lintiness.
This PR has an initial max count of 113 which should fail travis CI. Then I'll change it and it should pass.
> Set an upper limit on eslint warnings so that more cannot be merged

- src/components/Main/Results/DeterministicLinePlot.scss
- src/components/Main/Results/ResultsCard.scss
- Contributes to #83
Aims to align the text and icon of the ResultCards legends so it looks cleaner
ResultsCard
Visually tested, screenshot:
> [CSS] Make text and icons in charts align verticall

- cypress/integration/navigation.spec.ts
- cypress/integration/results.spec.ts
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.d.ts
- tslint.json
#101  😬
This PR fixes all the prettier+lint warning in the `cypress/` folder. It's a large PR, but confined to a single folder and built of atomic commits.
Linting and style warnings for all source code in the `cypress/` folder.
Manually check the style rules for `cypress/` only:
`npx eslint --report-unused-disable-directives --format codeframe "cypress/**/*.{js,jsx,ts,ts,json}"`
> #101/Lint and style all things Cypress

- src/algorithms/utils/TimeSeries.test.ts
- src/algorithms/utils/__snapshots__/TimeSeries.test.ts.snap
- src/types/jest.d.ts
Addresses concerns raised in #274 by implementing #281.
Jest snapshots are very useful because they can be updated from the test runner UI. But the default Jest snapshot assertion compares serialized strings. That causes problems if floats need to be compared. This PR implements a custom snapshot matcher for arrays of float values. It works by serializing expected results as a JSON array into the snapshot file. The snapshot can be deserialized and checked using a loop of toBeCloseTo() assertions. With this extension algorithm developers can use the Jest UI to add/update/remove snapshot results without modifying test logic.
This is a hack – it touches internal, private, Jest state. No guarantee this will continue to work if Jest is upgraded.
Unit tests
`yarn test TimeSeries`
> #274/WIP Implement a Jest extension to compare arrays of floats to snapshots.

- src/components/Main/state/reducer.ts
- fixes #307 
formik Field updates field value even when outside specified
min-max range (e.g. when updating with keyboard, not with arrows).
This allows for null value of numberPoints, or for value outside
desired 5-100 range, which may lead to 'Containment cannot be
empty' error in algorithms/run.ts. Added aditional validation
of numberPoints value in the reducer.
Behavior of mitigation curve when editing number of points with keyboard (it will not change when number of points is not within 5-100 range).
Try removing value of number of points with keyboard, or setting value which is not in the 5-100 range, mitigation curve should not change.
> validation of numberPoints in reducer

- src/algorithms/model.ts
Trivial PR. Fixing a leftover variable renaming. 
export. Now works again.
> fix wrong variable name in tsv export

- src/components/Main/Results/DeterministicLinePlot.tsx
This is related to #312  (already fixed) but catches more such problems. 
Also related to #154 
This PR abstracts our calculation of new cases and removes all empty data points from the graph. 
plot. 
inspect output. biggest change is expected for Germany where the case counts include data starting Jan 1st.
> filter empty data points to improve auto axis scaling in plot

- package.json
- src/components/Form/CardWithDropdown.tsx
- src/components/Form/CardWithoutDropdown.tsx
- src/components/Form/CollapsibleCard.tsx
- src/components/Form/FormHelpButton.scss
- src/components/Form/FormHelpButton.tsx
- src/components/Form/HelpLabel.tsx
- src/components/Layout/Layout.tsx
- src/components/Main/Main.tsx
- src/components/Main/Results/AgeBarChart.tsx
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/OutcomeRatesTable.tsx
- src/components/Main/Results/ResultsCard.scss
- src/components/Main/Results/ResultsCard.tsx
- src/components/Main/Scenario/ScenarioCard.tsx
- src/components/Main/Scenario/ScenarioCardContainment.tsx
- src/components/Main/Scenario/ScenarioCardEpidemiological.tsx
- src/components/Main/Scenario/ScenarioCardPopulation.tsx
- src/components/Main/Scenario/SeverityCard.tsx
- src/styles/_variables.scss
- src/styles/global.scss
- yarn.lock
This is a resubmit of  #195 by @arieltonglet rebased on current master.
Contributes to #83.
> Improve styles and readability v2

- src/components/Main/Main.tsx
- src/components/Main/Scenario/SeverityTable.tsx
- src/components/Main/Scenario/severityTableUpdate.ts
Contributes to #332
Creates the column. Does not send it to run() or any of the other requirements. 
Severity table
Initial values as expected, changes as scenarios change.
> add an age distribution / population column to the severity table

- src/components/LandingPage/LandingPage.scss
Fixes #321 
IE does not support `grid-gap` at IE10. 
https://medium.com/@elad/supporting-css-grid-in-internet-explorer-b38669e75d66
Removed it added a margin on the inner column and noticed no difference.
Also fixed some text overlap with the app image at widths <900>768.
Landing page
Viewed the landing page at various widths.
> Remove grid-gap

- src/components/App.tsx
- src/components/LandingPage/LandingPage.tsx
- https://github.com/neherlab/covid19_scenarios/issues/370
Query string now survives the landing page, so links shared via email will work, meaning the data from the URL will deserialize properly into a scenario.
There are a couple of PRs depending on this functionality:
https://github.com/neherlab/covid19_scenarios/pull/368, https://github.com/neherlab/covid19_scenarios/pull/366, https://github.com/neherlab/covid19_scenarios/pull/329
> fix: (370) Query string doesn't persist through landing page

- src/components/Main/state/URLSerializer.ts
Fixes #362, Related to #326 #338. Ignores #370.
Management of app state in browser URL was broken by #236. This change simply restores prior behavior and does not attempt to imagine a better way to manage and share app state. See #326 #338 et al for that.
Note: The scenario select does not display "Custom" on reload. That could be addressed as a new issue.
App state in the URL.
Go to the app. Change some parameters. Reload. The parameters are as changed.
> #362 quick fix for URL state tracking

- src/components/Main/Results/ResponsiveTooltipContent.tsx
- N/A
Removing warninga in browser console, to reduce noise:
ResponsiveTooltipContent.tsx
Click the Run button, then hover over the graph to see the tooltip. No warnings shouldn't be present in browser console after applying this PR.
> fix: (ResponsiveTooltipContent) Making label optional

- package.json
- src/algorithms/types/Param.types.ts
- src/components/Main/state/serialization/DtoConverter.test.ts
- src/components/Main/state/serialization/DtoConverter.ts
- src/components/Main/state/serialization/StateSerializer.test.ts
- src/components/Main/state/serialization/StateSerializer.ts
- src/components/Main/state/serialization/URLSerializer.test.ts
- src/components/Main/state/serialization/types/PersistedState.types.ts
- src/components/Main/state/serialization/types/PersistedStateDto.types.ts
- yarn.lock
- https://github.com/neherlab/covid19_scenarios/issues/326
Proposing alternative URL serialization (more read here: https://github.com/neherlab/covid19_scenarios/issues/326).
JSURL format: http://localhost:3000/?~(population~(ICUBeds~80~cases~%27CHE-Basel-Stadt~country~%27Switzerland~hospitalBeds~698~importsPerDay~0.1~populationServed~195000~suspectedCasesToday~10)~epidemiological~(infectiousPeriod~3~latencyTime~5~lengthHospitalStay~4~lengthICUStay~16~overflowSeverity~2~peakMonth~0~r0~2~seasonalForcing~0.2)~simulation~(simulationTimeRange~(tMax~1598918400000~tMin~1580428800000)~numberStochasticRuns~0)~containment~(~(y~1~t~1580428800000)~(y~1~t~1582483200000)~(y~0.6068708388814913~t~1584537600000)~(y~1~t~1586592000000)~(y~1~t~1588646400000)~(y~0.8250332889480693~t~1590700800000)~(y~1~t~1592 …
> feat: Using JSURL for data serialization in links

- src/components/Main/Main.tsx
- src/components/Main/Scenario/ScenarioCard.tsx
- src/components/Main/Scenario/ScenarioCardPopulation.tsx
- src/components/Main/Scenario/SeverityCard.tsx
- src/components/Main/Scenario/SeverityTable.scss
- src/components/Main/Scenario/SeverityTable.tsx
- src/components/Main/Scenario/validateInteger.ts
- src/components/Main/state/actions.ts
- src/components/Main/state/data.ts
- src/components/Main/state/reducer.ts
- src/components/Main/state/state.ts
- src/components/Main/validation/schema.ts
- Contributes to #332 
- Supersedes #369
- Punts URL serialization to a new issue yet to be opened.
Allow customization of age distribution.
Age distribution values.
- age distribution values set on initial load
- change when scenario or country drop downs change
- do not change when other form fields change
- edits are passed to run()
- ~~edits persist in the URL~~
- Age distribution country changes to Custom
- Cannot be negative
- Cannot be cleared
> Custom age distributions II

- package.json
- src/components/LanguageSwitcher/index.tsx
- src/helpers/numberFormat.ts
- src/i18n.ts
- src/langs.ts
- src/locales/de/index.ts
- src/locales/en/index.ts
- src/locales/es/index.ts
- src/locales/fr/index.ts
- src/locales/pt/index.ts
- yarn.lock
Fixes #158 
Replace numeral, with numbro, which has more i18n support
Rendering of numbers on results charts, tables.
Switch language to Polish, observe that numbers are abbreviated with locale appropriate abbreviations.
> Switch numeral to numbro

- src/components/Main/Results/ExportSimulationDialog.tsx
The last column of the table should be renamed, because the "Copy URL" option is not a download:
I'm proposing a better name:
> fix: Changing the Action column name

- src/components/Main/Mitigation/MitigationDatePicker.tsx
- src/components/Main/Mitigation/MitigationTable.scss
- src/components/Main/Mitigation/MitigationTable.tsx
- src/components/TestStandalone/MitigationTableTest.tsx
- src/pages/TestStandalone.tsx
- src/routes.ts
Fixes #383 
Provides a reasonable view of the mitigation form from very narrow through wide. Uses the width of the widget rather than media queries. Includes a standalone component test view route (only present when not production).
Mitigation interval input.
Wide -> Narrow & back.
Add & delete.
> Styling Mitigation Intervals

- src/components/Main/Main.tsx
- src/components/Main/state/serialization/StateSerializer.test.ts
- src/components/Main/state/serialization/URLSerializer.test.ts
- src/components/Main/state/serialization/URLSerializer.ts
Previously there were no named parameters in the URL's `location.search`. We're introducing the version variable, as well as the query variable.
* The reason for URL format versioning is because in the future we might completely change the way we serialize state to the URL
* For instance, maybe the amount of data needed to be persisted grows behind any advisable size, so we'll have to provide a stronger compression
* At that point, we might choose to replace JSURL with something else
* However, our users could still have the old link bookmarked accessible from some old email
* That's why we need version, as a separate link variable
* By reading the version first, and then applying a query deserialization for that version, we're ensuring backward compatibility
* Once we eventually start …
> feat: Introducing URL format versioning

- package.json
- src/components/Main/state/serialization/DtoConverter.ts
- src/components/Main/state/serialization/types/PersistedState.types.ts
- src/components/Main/state/serialization/types/PersistedStateDto.types.ts
- yarn.lock
Fixes #332 (final bit)
Adds any modifications to the age distribution fields to the serialized URL so they persist over shares and new tabs.
Custom age distributions.
Change an age pop number.
Open in new tab - check that the change persists.
Reload - check that the change persists.
New browser - check that the change persists.
> Add age distribution to serialization

- package.json
#450 
Was unable to run application using Windows 10 without getting Syntaxerror. Added backslashes to escape quotation marks in line 9 in package.json.
Package.json
> SyntaxError fix when running yarn dev, Windows 10

- src/pages/Loading.scss
#442 
- 
Move spinner farther down page. Set margin-top property in spinner container to 25%. Recommend testing with different browsers and sizes to make sure desired effect is achieved.
Loading.scss
Open main simulator page. Refresh page to view spinner.
> Center spinner

- cypress/integration/scenarios.spec.ts
- cypress/plugins/index.js
- cypress/support/commands.js
Contributes to #119  
Adding e2e tests for the scenario selector
- select a different scenario
- the correct values are set in the population card
- the correct values are set in the epidemiology card
Tests
run `yarn e2e` for a full test run
run `yarn e2e -s "**/scenario*"` to only run the scenario tests
> test: add tests for scenarios

- src/components/Main/Main.tsx
- src/components/Main/Results/ResultsCard.tsx
Contribtutes to #461, but does not implement 'sharing' feature. 
This remove auto-generation of the URL parameters.
WIP:
- ~~App needs to parse URL if present, and apply to scenario params.~~
- ~~Run in new tab needs to generate URL before opening window.~~
- ~~Run in new tab should be disabled if simulation cannot be run~~
Browser URL should be clean, no longer polluted by URL params.
"Run in tab" internal logic has changed, but should look unchanged to the user.
1. Open a fresh browser session
- Confirm there are no url params, i.e. URL should simply be `http://for.example.com/`
2. Change some scenario parameters.
- Confirm there are no url params.
3. Run the scenario.
- Confirm there are no url params.
4. "Run in new tab"
- A new tab should open, and the simulation should be run.
- The …
> #461/Remove autoupdating scenarioURL.

- src/components/Main/Main.tsx
Fixes #475 
The App uses Formik's validate method to trigger autorun. However it does not validate the date. And so the state used to run() is possibly invalid. 
This change uses the yup schema to validate the parameters and only updates state if they pass.
1. Mitigation table does not display validation errors. Perhaps that is fixed in #454 
2. There is double validation input to Formik. However removing `validationSchema=` disables validation. Possibly this is due to the debounced nature of `validate=`. 
Form validation
Auto run
```
with URL ingestion/update disabled
clear localStorage
load /
Set latency = -1
Focus out of input
=> Should be non-negative error displayed
Run is disabled
PASS
Enable auto run
run() is not triggered
PASS
Set latency = 4
run() is triggered with latency = 4 …
```
> #475/Validate before state update

- src/components/Main/Results/ExportSimulationDialog.tsx
- src/components/Main/Results/ResultsCard.tsx
Contributes to #461 
Fixes the broken "Shareable Link" export. The shareable link was being taken from the URL bar, but that is no longer a reliable source. This PR passes the shareable link as a param to the export modal.
Export.
1. Run a simulation
2. Click 'export'
3. Select "copy shareable link"
- Verify that the link contains URL params that resemble an exported scenario.
4. Paste the link into a new browser.
- Verify that the new simulation's scenario matches the exported scenario.
> Fix Export sharable URL

- src/styles/global.scss
Fixes #234 
This simple changes causes the tooltip to remain in view while the mouse is in the graph. Previously it would disappear and appear truncated due to being triggered by the scatter plots. 
Graph tooltips.
Mouse over the graph 🐭 📈
> Disable pointer events for scatter plot elements

- src/algorithms/model.ts
- src/algorithms/utils/exportResult.ts
- src/components/Main/Results/ExportSimulationDialog.tsx
Solves #504.
Generalizes the exportSimulation function to accept a variable number of arguments that are keys into userResult. If none are given, it will default to only reporting the total number for each category.
Will add an additional export category that downloads a large tsv table with all age stratified data.
model.ts
utils/exportResult.ts
Download tsv files and see that they are properly formatted.
> Allow for export of all stratified simulation data

- src/components/Main/Results/ChartCommon.ts
- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/LinePlotTooltip.tsx
Solves Issue #154.
As of now we have hardcoded in the assumption that the infectious window is 3 days in our display of new cases. This is suboptimal in the event that one wants to explore scenarios in which this differs from our default assumption. This PR solves this by parameterizing this computation by our input parameter. 
I've also kept in general insofar that I don't assume this is an integer as the infectious window we give is a average of a distribution so could in principle be a real number.
ChartCommon.ts
DeterminsticLinePlot.tsx
LinePlotTooltip.tsx
Check that the function behaves as expected on changing the infectious period.
> Variable number of new empirical cases now depends on infectious window.

- src/components/Main/Results/DeterministicLinePlot.tsx
The way empirical cases were added to plot resulted in them being registered at the first date of the interval, rather than the last date (as it should since they are called in new cases in the last three days, not next 3 days). This adds undefined to the array for the first 3 days. 
plot
double check plots.
> use 'undefined' for empirical cases prior to the difference window

- src/components/Main/Scenario/SeverityTable.scss
- src/components/Main/Scenario/SeverityTable.tsx
None
Tab focus when editing the Severity Table did not behave as expected, with this change:
- Tab moves focus to the next editable cell
- Only editable cells can get focus
- Edits only propagate when a change has occurred
Editing the age group (`SeverityTable`) grid.
Edit cells in the severity table and ensure that they propagate to run().
Both in the age distribution array and the severity table.
> Age group grid tab focus

- src/components/Main/HandleInitialState.test.tsx
- src/components/Main/HandleInitialState.tsx
- src/components/Main/Main.tsx
- src/components/Main/state/serialization/URLSerializer.test.ts
- src/components/Main/state/serialization/URLSerializer.ts
- src/pages/Home.tsx
None.
- Moves initial state and URL handling out of `<Main />`
- Uses react-router instead of direct window.location manipulation
- Tests initial state expectations
Initial state.
Land on /
form shows the initial state as expected
change vars
open in new tab
new tab shows the altered state as expected, url is /
reload and defaults are shown
export -> shareable link
Land on shareable link 
Page shows the altered state as expected, url is /
reload and defaults are shown
clear storage
reload
autorun should be disabled
click autorun
run() should occur
reload
autorun should be enabled
run() should occur
> refactor: move initial state handling out of Main

- src/components/Main/state/serialization/DtoConverter.test.ts
- src/components/Main/state/serialization/StateSerializer.test.ts
- src/components/Main/state/serialization/types/PersistedStateDto.types.ts
Related to #537 
Updates serialization (+tests) to support the changes to r0 and mitigationValue. i.e. they are now a range.
State sharing.
Set a range of value. Open in new tab. Range is present.
> bugfix: add range support to serialization

- src/components/Main/Results/LinePlotTooltip.tsx
Relates to #537 
Fix lint errors and '--' display on lower bounds with negative values.
Tooltips
yarn lint:tsc & eyeball tooltips at the lower end.
> Tooltip lint and display fixes re: uncertainty changes

- src/components/Main/validation/schema.ts
Contributes to #512 
Restores the schema for r0 & mitigationValue but as a tuple.
Form validity.
Change r0, mitigationValue.
Note: the slider widgets enforce their own schema so it is not possible to break the schema check.
> add schema for r0 & mitigationValue

- config/webpack/webpack.client.babel.ts
This moves `sourcemaps/` directory to the root of the deployed application, so that the source maps are autodeployed in production. As this is an open-source project, we don't have anything to hide.
dev experience
> feat: serve sourcemaps in production

- config/webpack/lib/webpackLoadJavascript.ts
- config/webpack/webpack.client.babel.ts
- 
This will make  package transpilation whitelist to only be processed in production mode.
This is necessary in order to account for the situation where the babel plugin of `@pmmmwh/react-refresh-webpack-plugin` adds variables inside a webworker, and which rely on globals that are not accessible in a webworker.
See discussion here:
https://github.com/neherlab/covid19_scenarios/pull/505#discussion_r410737067
https://github.com/neherlab/covid19_scenarios/pull/505#discussion_r411049698
As a workaround we disable the transpilation of `node_modules` completely in dev mode (the default behavior of babel loader), and only process additional packages in production, where fast refresh is disabled.
Build.
:no_good:
> chore: only process package transpilation whitelist in production

- src/components/Form/FormRangeSpinBox.tsx
- src/components/Form/RangeSpinBox.tsx
- src/components/Form/SpinBox.tsx
- src/components/Main/Mitigation/MitigationTable.tsx
- src/components/Main/Scenario/ScenarioCardEpidemiological.tsx
- src/helpers/getFormikError.ts
- Contributes to #580 
This explores the user experience with 
- a pair of spinboxes as a mean to set ranges of numbers for the parameter uncertainty feature
- table layout for the mitigation widget
UX
> feat: replace range sliders with pairs of spinboxes

- config/webpack/webpack.client.babel.ts
No relation.
Removes the duplicated `'immer'` listed in the webpack config `transpiledLibs` array. The duplication is harmless but unnecessary. Probably a merge artifact.
Production Webpack bundling.
`yarn prod:build`
> Remove duplicated 'immer' in webpack transpiledLibs.

- data/scripts/scenarios.py
- schemas/Scenarios.yml
- src/algorithms/initialize.ts
- src/algorithms/mitigation.ts
- src/algorithms/utils/sample.ts
- src/assets/data/scenarios/scenarios.json
- src/components/Main/Scenario/ScenarioCardPopulation.tsx
- src/components/Main/validation/schema.ts
- Contributes to #537 
This makes number of runs user-adjustable. Currently with a spinbox.
Notes:
- spinbox might be changed to something else (e.g. a slider)
- Schema:
-  We reuse `AllParams.Simulation.numberStochasticRuns` from the existing schema. 
- Therefore the number has to be provided from the data repo. It does not make mch sense as the parameter is hardcoded. It does not depend on scenario itself. We only are even concerned about it before simulation.
- The cleaner way would be to move it into a separate schema.
- However this make serialization logic differ between data repo files and URL/params file (we want to have numberStochasticRuns in the URL but not in data repo)
- This means AllParams are not really all the params, but there are separate scenario params and …
> feat: make number of runs user-adjustable

- schemas/Scenarios.yml
- src/components/Main/Scenario/ScenarioCardPopulation.tsx
- src/components/Main/validation/schema.ts
- Related to issue #581, #582  
- "spinbox limit min to 10"
Set spinbox minimum value to 10 in Scenarios.yml; modified error msg in schema.ts to "Should be at least ten."
schemas/Scenarios.yml
src/components/Main/validation/schema.ts
> feat: set spinbox minimum to 10 runs

- src/workers/algorithm/index.ts
#612 reveals the issue, and #505 is the original implementation.   
There is an unnecessary console.error() log in the webworker. This PR removes the extra call.
Webworker error logging. 
Difficult to test without an error, but #612 provides and indirect example of the behavior.
> Remove unncessary console.error

- src/algorithms/types/Param.types.ts
- src/components/Main/state/serialization/types/PersistedState.types.ts
- src/components/Main/state/state.ts
Addresses a Fixme:
Refactor to eliminate `ScenarioData` type alias in favor of `AllParams`. Both types are used in the code. `AllParams` is by far the most the most popular.
Slight impact on developer experience since `ScenarioData` type no longer exists.
> Replace ScenarioState type with the identical AllParams type.

- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/LinePlotTooltip.tsx
- src/components/Main/Results/R0LinePlot.tsx
Issue #581 
Gives a tooltip to our plot of the dynamic effective reproductie number
DeterministicLinePlot.tsx
LinePlotTooltip.tsx
R0LinePlot.tsx
Open up the application and see with your eyes.
> Tooltip for effective reproductive number

- schemas/AgeDistributionDatum.yml
- 
Allows 0 for population value in age distribution schema
> fix: allow for population of 0 in age distribution

- src/components/Main/HandleInitialState.tsx
- src/components/Main/ScenarioLoader/ScenarioLoaderUploader.tsx
- src/components/Main/state/actions.ts
- src/components/Main/state/reducer.ts
- src/components/Main/state/state.ts
Related issues and PRs
- Fixes #653
This adds a boolean flag to the state and changes scenario state reducer logic such that the user-provided scenario title is preserved at all times.
> feat: preserve user-provided scenario name on parameter change

- src/components/Main/HandleInitialState.tsx
- 
This makes sure that the severity table is restored from the shared URL.
The issue was that the severity data was deserialized, but ignored and default data was loaded instead.
UI, initial state
> Ensure severity table is restored from URL

- src/components/Main/Results/ResultsCard.tsx
- 
Hides "expand" results button on lg screens and smaller, as expand function does not work there (not enough space)
> fix: hide "expand" results button on lg screens and smaller

- src/components/Layout/Footer.tsx
- Fixes #660 
Add padding to footer and justify content correctly from mobile to larger screens.
Footer component (`Footer.tsx`)
> made footer layout mobile responsive

- package.json
- yarn.lock
`snyk protect` command was crashig with:
```
$ yarn snyk-protect
yarn run v1.22.4
$ snyk protect
Error: Cannot find module 'core-js/library/fn/set-immediate'
Require stack:
- node_modules/snyk-nuget-plugin/node_modules/jszip/lib/utils.js
- node_modules/snyk-nuget-plugin/node_modules/jszip/lib/utf8.js
- node_modules/snyk-nuget-plugin/node_modules/jszip/lib/object.js
- node_modules/snyk-nuget-plugin/node_modules/jszip/lib/index.js
- node_modules/snyk-nuget-plugin/dist/nuget-parser/nuspec-parser.js
- node_modules/snyk-nuget-plugin/dist/nuget-parser/dotnet-framework-parser.js
- node_modules/snyk-nuget-plugin/dist/nuget-parser/index.js
- node_modules/snyk-nuget-plugin/dist/index.js
- node_modules/snyk/dist/lib/plugins/index.js
- node_modules/snyk/dist/lib/plugins/get-single-plugin-result.js
- …
```
> fix: fix crash when running snyk protect

- src/components/Main/Results/DeterministicLinePlot.tsx
- src/components/Main/Results/Utils.test.ts
- src/components/Main/Results/Utils.ts
Related to [this Fixme](https://github.com/neherlab/covid19_scenarios/blob/1a382d629a300b549f6b5559378921b0f80bc191/src/components/Main/Results/DeterministicLinePlot.tsx#L107), an incremental refactoring of the DeterministicLinePlot component.
(Additional context: #636, #671)
Reduce the code complexity of `DeterministicLinePlot.tsx` by extracting the `computeNewEmpiricalCases()` methods into a utility module. Also adds units tests for the method to aid future refactoring.
Slight reorganization of the code. Adds more unit tests.
Adds units tests for `computenewEmpiricalCases` in the `Utils.ts` module.
Run `yarn test` to test.
> Refactor computeNewEmpiricalCases into module with unit tests.

- src/components/Main/Results/DeterministicLinePlot.tsx
Related to [this Fixme](https://github.com/neherlab/covid19_scenarios/blob/1a382d629a300b549f6b5559378921b0f80bc191/src/components/Main/Results/DeterministicLinePlot.tsx#L107), an incremental refactoring of the DeterministicLinePlot component.
(Additional context: #636, #671, #677)
Reduce the code complexity of `DeterministicLinePlot.tsx` by using computed property names to associate caseCounts with plotted data. This refactoring reduces the number of conditional statements and improves communication of intention.
Functionality unchanged, but the code `DeterministicLinePlot.tsx` is slightly changed. 
No unit tests were added by this change.
> Refactor DeterministiclinePlot's caseCount -> observationsToPlot filter.

- src/algorithms/cli.ts
- Related to https://github.com/neherlab/covid19_scenarios/issues/663, though not yet a fully-featured CLI.
This PR adds a simple CLI entry point that:
- reads input JSON (of type `ScenarioData`) from a specified input path
- runs the model by calling into `run.ts`
- writes output JSON (of type `AlgorithmResult`) into the specified output path
This allows the model to be run in a unified model UI, such as the one we are maintaining at https://github.com/covid-modeling on the GitHub side. We are already using a version of this at https://github.com/covid-modeling/model-runner to run this model, but are currently tied to my fork that has the CLI entry point and an older version of your model. Having this code as part of the model repo enables the unified interface to keep up with model …
> Add a simple CLI for use in unified model interface

- src/components/Main/Results/PlotSpinner.tsx
- src/components/Main/Results/ResultsCard.scss
- src/components/Main/Results/ResultsCard.tsx
- src/styles/_variables.scss
- add progress indicator to the result section #688 
- create a spinner when the plot is loading. The spinner is aligned with the indicator to the button.
- add PlotSpinner component which renders the spinner logo. 
- add ternary logic to the plot components so that when the result "isRunning", it will render the spinner icon. Otherwise, it will the normal components
- edit result css file to centre the spinner icon
> add progress indicator to the result section

- docs/command_line.md
- package.json
- src/algorithms/cli.ts
- yarn.lock
Add a yarn target for running the model via the command line.
These changes allow the model to be run via the command line via a `yarn cli` call. Two arguments are required: `--scenario` and `--out`.
The changes are all pretty trivial. Some command line parsing is done via `yargs` in `src/algorithms/cli.ts` (and so a dependency is introduced on the [yargs](http://yargs.js.org/) package in `package.json`).
1. Copy the example scenario parameters shown on `docs/comand_line.md` into a file `scenario.json`.
1. At the command line, execute `yarn cli --help` to see the usage message.
1. At the command line, execute `yarn cli --scenario=scenario.json --out=output.json`.
1. Confirm that `output.json` was created by the run and has reasonable-looking output.
* We are using these mods as we do some …
> Command line runs

- package.json
- src/algorithms/mitigation.ts
- src/assets/text/updates.md
production version uses only one sample from the mitigation intervals which seems related to oddities of `[...Array(numberStochasticRuns).keys()]` in the production environment. 
`Array(numberStochasticRuns).fill(1)` returns a mappable array that does the trick
check whether uncertainty is properly handled for mitigations
> ensure mitigation intervals are correctly sampled in production

- babel.config.js
Related to the issue resolved in https://github.com/neherlab/covid19_scenarios/pull/729.
#729 solves the problem for this particular piece of code, while this PR aims to resolve the root cause globally.
This disables loose transformations in babel, to avoid inconsistencies between different environments.
In particular, this code is transpiled differently  in dev and prod when `loose` is enabled:
```
[...Array(numberStochasticRuns).keys()]
```
Additionally, this disables "shipped proposals", just in case, as it is a risky option too.
See also: 
- https://babeljs.io/docs/en/babel-plugin-transform-spread#loose
- https://github.com/babel/babel-preset-env/issues/76
- https://babeljs.io/docs/en/babel-preset-env#loose
Build, transpilation.
> fix: disable loose transformations and shipped proposals in babel

- data/scripts/getPopulationData.py
Was unable to run `python generate_data.py --output-population ../src/assets/data/population.json` due to a name change of a hard-coded path in the script and a change made to the structure of an input json file. 
Error for file path: 
`No such file or directory: '../src/assets/data/country_age_distribution.json'`
Error for json structure change: 
`return country in [x['country'] for x in ages] `
`TypeError: string indices must be integers`
Updating population data
`python generate_data.py --output-population test.json`
> fix: adjust getPopulationData.py to account for input file change

- package.json
- yarn.lock
This was due to the upgrade of the `history` package in #762. History v5 is not compatible with our setup.
> fix: fix crash when navigating to a page

- README.md
Adds links in readme for direct access to translations on GitLocalize.
> docs(readme): add links to translations

- src/io/serialization/v2.0.0/serialize.ts
- src/io/serialization/v2.1.0/serialize.ts
This fixes an error "/schemaVer should be equal to constant" when dropping a  JSON file with schemaVer < 2.2.0 in scenario loader.
> fix: load scenario json from older versions

- src/components/Updates/UpdatesContent.md
add  information to release notes and close the bug as solved.
"The case-count export was restricted to the last 200 days, assuming that most people study recent dynamics. "
> added info to release notes
